FROM maven:3.8-openjdk-17-slim

COPY . /app

WORKDIR /app

RUN mvn dependency:resolve -f app/pom.xml

RUN mvn package -f app/pom.xml

RUN app/target/app.jar .

RUN rm -rf app/

COPY --from=builder /app /app

WORKDIR /app

CMD [ "java", "-jar", "app.jar" ]

